### ISSUE TITLE
sampler stats

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#46]
file: https://github.com/pymc-devs/pymc-examples/blob/main/examples/diagnostics_and_criticism/sampler-stats.ipynb

## Required changes
The notebook should use InferenceData and ArviZ for plotting. Note that the names of the sampler stats in ArviZ are different, the naming convention for ArviZ can be found at https://arviz-devs.github.io/arviz/schema/schema.html#sample-stats, doc which should be linked too.

## Changes for discussion
I think it would be a good addition to add a plot_parallel as a quick way to visualize divergences or to link to the notebook on divergences.

**Comment by almostmeenal** [comment]
that sounds like a good idea, I feel like adding more math-y info of those stats would be helpful, because in this notebook I think there's just trace.stat_names, which is sort of just documentation all over again, probably example notebooks should be doing more, I think what I'm trying to say is they can be somewhat pedagogical, I don't know if i make a lot of sense. But I'll be happy to work on it

**Comment by canyon289** [comment]
Assigned you @almostmeenal. Based on our early conversations regarding GSOC and your interests this seems like a great one to both help you work on the types of OSS youd like to, as well as to keep building up your experience for a strong application (for any project you apply to)!

**Comment by almostmeenal** [comment]
thanks! I'll get to it soon, yes this does look like a right fit.
