### ISSUE TITLE
thumbnails not showing on notebooks home page

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-examples#479]
**Notebook title**:
**Notebook url**:

Thumbnails are not showing here:
https://www.pymc.io/projects/examples/en/latest/gallery.html

<img width="551" alt="Screen Shot 2022-12-19 at 12 29 42 PM" src="https://user-images.githubusercontent.com/2507232/208484916-dbbbf20c-973d-4361-9894-a477a1d60b1d.png">

**Comment by twiecki** [comment]
Probably due to https://github.com/pymc-devs/brand/pull/21

**Comment by reshamas** [comment]
Arrgh! Disliking breaking changes.  :(

**Comment by drbenvincent** [comment]
These notebooks exist here `https://github.com/pymc-devs/pymc/tree/main/docs/source/learn/core_notebooks` rather than in the `pymc-examples` repo. Personally I think this creates a bit of added complexity. What do people think about moving them into the `pymc-examples` repo?

I think the logic of having them in `pymc-devs/pymc` was to make sure that these are always up to date with the latest API. But I think we can just achieve the same result if we treat these as 'core' and of high importance, but in the `pymc-examples` repo.

What do people think?

**Comment by twiecki** [comment]
That makes sense to me.

**Comment by OriolAbril** [comment]
trying to think about the workflow to ensure the core notebooks are always up to date with the codebase I find it more complicated. I am not sure users know or even care the page they go to when they click on those first cards are generated from a different repo.

How do you envision the updated workflow to be?

For comparison, he current one is any time a change breaks a core notebook, CI fails for that PR and the notebook is updated in the same PR that modified the related code. Every PR and every build on latest _execute_ all core notebooks on the corresponding local github version.

**Comment by ricardoV94** [comment]
I think it makes sense for the core notebooks to work as they do now. It must be possible to fix the thumbnails some other way.

**Comment by OriolAbril** [comment]
Thumbnails are already fixed by the way, we just forgot to close the issue

**Comment by reshamas** [comment]
Closed by https://github.com/pymc-devs/pymc-examples/pull/480
