### ISSUE TITLE
rugby analytics

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#49]
file: https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/rugby_analytics.ipynb

## Required changes
The inital exploratory analysis looks ok, seaborn is an ok dependency for this, the model needs to be updated, no flat priors for example and we should also use coords+dims and ArviZ for posterior analysis and exploration.

*Notes:* updates on the model and priors can be taken from https://github.com/arviz-devs/arviz_example_data/blob/main/rugby.ipynb.

**Comment by almostmeenal** [comment]
@OriolAbril can I take this

**Comment by canyon289** [comment]
Assigned to this as well. I would suggest closing the two you're assigned to before taking on any more PRs

**Comment by almostmeenal** [comment]
ran into some error- https://github.com/arviz-devs/arviz/pull/1117#issuecomment-808915434 , also random but would it be a good idea to possibly create a similar example notebook with something like ucl or something, with recent data and current best practices, I saw that this notebook didnt even import arviz. can something be done to ensure examples get updated accordingly each time a new PR is merged which revamps/removes/modifies/adds a new feature or utility to ensure they stay updated. I mean, as contributors yeah we can look up errors and everything but for users who want to learn from examples repo, running into errors there is kind of hard to fix.

**Comment by twiecki** [comment]
@almostmeenal Yes, I think updating the NBs to use best current practices is important, like arviz and `coords`.

**Comment by almostmeenal** [comment]
@OriolAbril hi so I'm thinking a lot of things and I'm slightly lost wrt what exactly am i supposed to do, so I'll start a pull request while I'm working on it so you can maybe help me out a bit, from what I think, I guess I'm supposed to change the part after building the model and use arviz inference data format for data and arviz plots instead of the ones used. and for building the model take the part from rugby.ipynb in arviz_example_data

**Comment by OriolAbril** [comment]
Sending a PR sounds great! I have been adding more and more guidance and content but I can't go as fast as I'd like. For now you'll see I have already added a [contributing guide](https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md) that is specific to pymc-examples and when you submit the PR, you'll see I have also added a pull request template. 

> I guess I'm supposed to change the part after building the model and use arviz inference data format for data and arviz plots instead of the ones used

yes, these changes would "move" the notebook from "To Do" to "ArviZ" column.

> and for building the model take the part from rugby.ipynb in arviz_example_data

and these changes would move from "To Do" to "General updates", if all changes in here and the point above are done, then the notebook would end up placed in "Best Practices". I hope the explanation on the contributing guide is also clear on that (if not please let me know how to improve it). Note however that the model in arviz_example_data is an starting point, there are still some more updates to do like using `coords` and `dims` when building the model.

**Comment by almostmeenal** [comment]
thankyou!! i read the guide and um here's the  PR, https://github.com/pymc-devs/pymc-examples/pull/62
I changed a few plots to arviz wherever I could, for some I'm still a lil confused. The inference data is arviz style and the plots use coords, and replaced old functions like pm.hpd with az.hdi. I was wondering how to use az.quantile since there's a line using "np.quantile" and I figured we could try that. So yeah, its definitely a WIP but moving towards good practices.
