### ISSUE TITLE
Broken link in MLDA example notebook

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymc-examples#619]
**Notebook title**: The MLDA sampler
**Notebook url**: https://www.pymc.io/projects/examples/en/latest/samplers/MLDA_simple_linear_regression.html

## Issue description
The notebook contains this text:
> The model is similar to the one used in https://docs.pymc.io/notebooks/GLM-linear.html.

But the URL is not a link and is non-operational.

## Proposed solution
The linking explanatiion/guidance found [here](https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html#myst-guidelines) should be used to appropriately use sphinx links to the relevnat notebook.

**Comment by OriolAbril** [comment]
The url should be replaced by `` {ref}`pymc:glm_linear` ``

**Comment by pradyutf** [comment]
Hi @cluhmann ,

I saw the solution proposed in the comments for this issue, and I believe it will fix the problem because it follows the guidelines and has been referenced in a file. I've attached a screenshot for reference.
<img width="621" alt="Screenshot 2024-07-30 at 12 08 05 AM" src="https://github.com/user-attachments/assets/67de4b36-af4b-4c6e-ad6c-2c2d582991fb">


Would you like me to raise a PR to implement this fix?

Thanks

**Comment by cluhmann** [comment]
That would be fantastic!
